---

- name: Ensure the azure-cli install directory exists
  file:
    path: "{{ azcli_install_dir }}"
    state: directory

- name: Ensure the azure-cli bin directory exists
  file:
    path: "{{ azcli_bin_dir }}"
    state: directory
  when: azcli_install_venv_helper is defined
        and azcli_install_venv_helper

- name: Ensure Python 3 interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ azcli_python3_path }}"

- name: Ensure azure-cli is installed in a virtual environment
  pip:
    name: azure-cli
    version: "{{ azcli_version }}"
    state: present
    virtualenv: "{{ azcli_install_dir }}/azure-cli-{{ azcli_version }}"
    virtualenv_command: "{{ azcli_python3_path }} -m venv"

- name: Ensure the originally configured Python interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ azcli_ansible_python_interpreter }}"
  when: azcli_ansible_python_interpreter is defined

- name: Ensure the current release is symlinked in the install directory
  file:
    src: "{{ azcli_install_dir }}/azure-cli-{{ azcli_version }}"
    dest: "{{ azcli_install_dir }}/{{ azcli_current_dirname }}"
    state: link

- name: Ensure venv wrapper exists in virtualenv bin directory
  template:
    src: venv.sh.j2
    dest: "{{ azcli_install_dir }}/azure-cli-{{ azcli_version }}/bin/venv"
    mode: 0755
  loop:
    - python

- name: Ensure venv helper exists for az in bin directory
  template:
    src: venv.sh.j2
    dest: "{{ azcli_bin_dir }}/{{ item }}"
    mode: 0755
  loop:
    - az
  when: azcli_install_venv_helper is defined
        and azcli_install_venv_helper
