---

- name: Check to see if the azure-cli version directory exists
  stat:
    path: "{{ azcli_install_dir }}/{{ azcli_venv_name }}-{{ azcli_venv_suffix }}"
  register: azcli_check_version_dir

- name: Fail if the azure-cli version directory doesn't exist
  fail:
    msg: "{{ azcli_install_dir }}/{{ azcli_venv_name }}-{{ azcli_venv_suffix }} is missing after play."
  when: not azcli_check_version_dir.stat.exists

- name: Check to see if the azure-cli current symlink exists
  stat:
    path: "{{ azcli_install_dir }}/{{ azcli_venv_name }}"
  register: azcli_check_symlink_dir

- name: Fail if the azure-cli symlink directory doesn't exist
  fail:
    msg: "{{ azcli_install_dir }}/{{ azcli_venv_name }} symlink not correct after play."
  when: not azcli_check_symlink_dir.stat.exists
        or not azcli_check_symlink_dir.stat.islnk
        or azcli_check_symlink_dir.stat.lnk_target != (azcli_install_dir + "/" + azcli_venv_name + "-" + azcli_venv_suffix)

- name: Check to see if the azure-cli version directory is a virtualenv
  stat:
    path: "{{ azcli_install_dir }}/{{ azcli_venv_name }}/bin/activate"
  register: azcli_check_virtualenv_dir

- name: Fail if the azure-cli virtualenv directory doesn't exist
  fail:
    msg: "{{ azcli_install_dir }}/{{ azcli_venv_name }}/bin/activate not found after play."
  when: not azcli_check_virtualenv_dir.stat.exists
        or not azcli_check_virtualenv_dir.stat.isreg
