---

- name: Check the path for Python
  command: which python3
  register: azcli_check_python_3_path
  failed_when: azcli_check_python_3_path.rc > 0
  changed_when: false
  when: azcli_python3_path is not defined

- name: Ensure the path to Python 3 is set as a fact
  set_fact:
    azcli_python3_path: "{{ azcli_check_python_3_path.stdout }}"
  when: azcli_python3_path is not defined
