---
- name: Converge
  hosts: all
  become: true
  vars:
    azcli_install_os_dependencies: true
    azcli_install_dir: /opt/azcli/bin
    azcli_current_dirname: current
  roles:
    - role: xanmanning.azcli
