---

- name: Ensure gcc, Python 3 and Python Pip is installed (YUM)
  yum:
    name:
      - gcc
      - python3
      - python3-devel
      - python3-pip
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Ensure gcc, Python 3 and Python Pip is installed (DNF)
  dnf:
    name:
      - gcc
      - python3
      - python3-devel
      - python3-pip
    state: present
  when: ansible_pkg_mgr == "dnf"
